// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AchievementsController from "./achievements_controller"
application.register("achievements", AchievementsController)

import CartController from "./cart_controller"
application.register("cart", CartController)

import CounterController from "./counter_controller"
application.register("counter", CounterController)

import DropTimerController from "./drop_timer_controller"
application.register("drop-timer", DropTimerController)

import GameHudController from "./game_hud_controller"
application.register("game-hud", GameHudController)

import GlobalMapController from "./global_map_controller"
application.register("global-map", GlobalMapController)

import MenuController from "./menu_controller"
application.register("menu", MenuController)

import PassportController from "./passport_controller"
application.register("passport", PassportController)

import PreloaderController from "./preloader_controller"
application.register("preloader", PreloaderController)

import RevealController from "./reveal_controller"
application.register("reveal", RevealController)

import ScrollTrackerController from "./scroll_tracker_controller"
application.register("scroll-tracker", ScrollTrackerController)

import TestimonialsController from "./testimonials_controller"
application.register("testimonials", TestimonialsController)

import TickerController from "./ticker_controller"
application.register("ticker", TickerController)

import XpSystemController from "./xp_system_controller"
application.register("xp-system", XpSystemController)
